<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use BezhanSalleh\FilamentShield\Support\Utils;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         // Create or get 'admin' role
        $adminRole = Role::firstOrCreate(['name' => 'admin']);

        // Give the role all permissions generated by Filament Shield
        $permissions = Permission::all();
        $adminRole->syncPermissions($permissions);

        // Create the default admin user
        $adminUser = User::firstOrCreate(
            ['email' => 'admin@lijo.co.ls'],
            [
                'name' => 'Super Admin',
                'phone' => '57802943',
                'password' => Hash::make('admin'), // Change this in production
            ]
        );

        // Assign role
        $adminUser->assignRole($adminRole);
    }
}
